# Generated by Django 4.1.1 on 2022-09-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bitcoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
