# Generated by Django 4.1.1 on 2022-09-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_bitcoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoin_price',
            name='price',
            field=models.FloatField(),
        ),
    ]
